### ISSUE TITLE
Cache does not work. Cache status is always bypass

### ISSUE THREAD

**Issue by ishuvalov** [sillygod/cdp-cache#47]
Hello,

Whatever I write to configuration, requests are always passed to the upstream and returned cache status header contains `bypass`.
Here id a handler part of my YAML caddy config. Could you please provide some hint to proper configuration? Thanks
```
            - handler: http_cache
              config:
                status_header: X-Cache-Status
                cache_key_template: "{http.request.scheme}{http.request.host}{http.request.uri.path}"
                cache_max_memory_size: 1073741824
                default_max_age: 600000000
                lock_timeout: 60000000000
                type: in_memory
                rule_matcher_raws:
                  - Data:
                      path: /
                    Type: path
            - handler: reverse_proxy
              upstreams:
                - dial: "#{$UPSTREAM}"
```
